# Description: Logical Vectors in R

# Logical Vectors
# 1. The elements of a logical vector can have the values TRUE, FALSE, and NA (for “not available”).
# 2. The TRUE and FALSE are often abbreviated as T and F, respectively. However that T and F are just variables which
#    are set to TRUE and FALSE by default, but are not reserved words and hence can be overwritten by the user. Hence,
#    you should always use TRUE and FALSE explicitly.
x <- c(T, F)
x <- c(TRUE, FALSE, FALSE, TRUE)
print(x)

# 3. Logical vectors are generated by conditions.
y <- c(1, 13, 14, 20, NA, NaN)
result <- x > 13

# 4. Logical Operators
result <- x < 13                        # Less Than
result <- x <= 13                       # Less Than or Equal To
result <- x > 13                        # Greater Than
result <- x >= 13                       # Greater Than or Equal To
result <- x == 13                       # Equal To for EXACT EQUALITY
result <- x != 13                       # Not Equal To

# 5. Union, Intersection and Negation
condition1 <- TRUE
condition2 <- FALSE
result <- condition1 & condition2       # The result is their intersection (“and”)
result <- condition1 | condition2       # The result is their union (“or”)
result <- !condition1                   # The result is the negation (“not”)
print(result)

# 6. Logical Values in Arithmetic Expressions: Logical vectors may be used in ordinary arithmetic, in which case they
#    are coerced into numeric vectors, FALSE becoming 0 and TRUE becoming 1. However there are situations where logical
#    vectors and their coerced numeric counterparts are not equivalent.

# TODO
# * None
